## 1. 함수

### 1-1. 값을 반환하지 않는 함수

In [11]:
def func1():
    print(1)
    
def func2(x):
    print(x)
    
def func3(x=1):
    print(x)

In [12]:
func1()
func2(1)
func3()

1
1
1


### 1-2. 값을 반환하는 함수

In [13]:
def func1():
    return 1
    
def func2(x):
    return x
    
def func3(x=1):
    return x

In [8]:
func1()

1

In [9]:
func2(1)

1

In [10]:
func3()

1

#### Q. 1000만건의 문자 메시지를 보내려고합니다. 내용은 같지만, 고객의 이름을 다 언급하기 위해, 메시지의 시작을 특정 고객의 이름을 언급하면서 시작하려고 합니다. 고객의 이름을 넣어주는 함수를 만들어주세요

In [17]:
def greeting(text,name):
    #여기에 코드 작성
    return text

message = "명절 잘 보내세요!"
greeting(message,"서중원")

'명절 잘 보내세요!'

## 2. Numpy

In [44]:
import numpy as np

In [45]:
arr1 = [1,2,3]
arr2 = [4,5,6]

In [46]:
#arr1+arr2 동일한 위치에 있는 원소들끼리 합을하려면?
arr3 = [0]*len(arr1)
for index, _ in enumerate(arr3):
    arr3[index] = arr1[index]+arr2[index]
arr3

[5, 7, 9]

In [47]:
arr1 = np.array(arr1)
arr2 = np.array(arr2)
arr3 = arr1 + arr2
arr3

array([5, 7, 9])

In [48]:
mask = arr3>5
mask

array([False,  True,  True])

In [49]:
arr3[mask]

array([7, 9])

In [50]:
arr = np.random.randint(1,10,16)
arr

array([9, 6, 2, 5, 9, 7, 9, 1, 8, 6, 7, 8, 7, 2, 1, 1])

In [51]:
arr[:]=10
print(arr)
#arr=10

[10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10]


In [52]:
arr[:]*=2
arr

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

#### Q. Min-Max스케일링은 수치범위가 넓은 feature에 대해 정규화를 하는 방식입니다. 다음 공식을 활용하여 해당 값을 정규화 하세요!

$x_{norm} = \frac{X-X_{min}}{X_{max}-X_{min}}$

In [86]:
data = np.random.randint(1,1000,16)
data = data.astype(float)
data

array([984., 544., 679., 464., 245., 231., 967., 558., 645., 259., 985.,
       935., 152., 265., 504., 318.])

In [87]:
#여기에 코드작성

## 3. Pandas

In [90]:
# Pandas는 데이터를 확보한 후 부터 유의미한 Library
import pandas as pd

In [91]:
df = pd.read_csv("data/train.csv")
df.head()

아이디  생존  객실등급                                                 이름      성별  \
0    1   0     3                            Braund, Mr. Owen Harris    male   
1    2   1     1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2    3   1     3                             Heikkinen, Miss. Laina  female   
3    4   1     1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4    5   0     3                           Allen, Mr. William Henry    male   

     나이  형제자매  부모              티켓번호       요금  객실번호 승선항  
0  22.0     1   0         A/5 21171   7.2500   NaN   S  
1  38.0     1   0          PC 17599  71.2833   C85   C  
2  26.0     0   0  STON/O2. 3101282   7.9250   NaN   S  
3  35.0     1   0            113803  53.1000  C123   S  
4  35.0     0   0            373450   8.0500   NaN   S

In [92]:
#컬럼 기반 접근에 최적화
df['나이']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
5       NaN
6      54.0
7       2.0
8      27.0
9      14.0
10      4.0
11     58.0
12     20.0
13     39.0
14     14.0
15     55.0
16      2.0
17      NaN
18     31.0
19      NaN
20     35.0
21     34.0
22     15.0
23     28.0
24      8.0
25     38.0
26      NaN
27     19.0
28      NaN
29      NaN
       ... 
861    21.0
862    48.0
863     NaN
864    24.0
865    42.0
866    27.0
867    31.0
868     NaN
869     4.0
870    26.0
871    47.0
872    33.0
873    47.0
874    28.0
875    15.0
876    20.0
877    19.0
878     NaN
879    56.0
880    25.0
881    33.0
882    22.0
883    28.0
884    25.0
885    39.0
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: 나이, Length: 891, dtype: float64

In [94]:
#결측값 처리에 용이
df["나이"].dropna()


0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
6      54.0
7       2.0
8      27.0
9      14.0
10      4.0
11     58.0
12     20.0
13     39.0
14     14.0
15     55.0
16      2.0
18     31.0
20     35.0
21     34.0
22     15.0
23     28.0
24      8.0
25     38.0
27     19.0
30     40.0
33     66.0
34     28.0
35     42.0
37     21.0
38     18.0
       ... 
856    45.0
857    51.0
858    24.0
860    41.0
861    21.0
862    48.0
864    24.0
865    42.0
866    27.0
867    31.0
869     4.0
870    26.0
871    47.0
872    33.0
873    47.0
874    28.0
875    15.0
876    20.0
877    19.0
879    56.0
880    25.0
881    33.0
882    22.0
883    28.0
884    25.0
885    39.0
886    27.0
887    19.0
889    26.0
890    32.0
Name: 나이, Length: 714, dtype: float64

In [95]:
df["나이"].fillna(100)

0       22.0
1       38.0
2       26.0
3       35.0
4       35.0
5      100.0
6       54.0
7        2.0
8       27.0
9       14.0
10       4.0
11      58.0
12      20.0
13      39.0
14      14.0
15      55.0
16       2.0
17     100.0
18      31.0
19     100.0
20      35.0
21      34.0
22      15.0
23      28.0
24       8.0
25      38.0
26     100.0
27      19.0
28     100.0
29     100.0
       ...  
861     21.0
862     48.0
863    100.0
864     24.0
865     42.0
866     27.0
867     31.0
868    100.0
869      4.0
870     26.0
871     47.0
872     33.0
873     47.0
874     28.0
875     15.0
876     20.0
877     19.0
878    100.0
879     56.0
880     25.0
881     33.0
882     22.0
883     28.0
884     25.0
885     39.0
886     27.0
887     19.0
888    100.0
889     26.0
890     32.0
Name: 나이, Length: 891, dtype: float64

In [98]:
#추가 컬럼 생성에도 용이!
df['이름길이'] = df['이름'].apply(len)
df.head()

아이디  생존  객실등급                                                 이름      성별  \
0    1   0     3                            Braund, Mr. Owen Harris    male   
1    2   1     1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2    3   1     3                             Heikkinen, Miss. Laina  female   
3    4   1     1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4    5   0     3                           Allen, Mr. William Henry    male   

     나이  형제자매  부모              티켓번호       요금  객실번호 승선항  이름길이  
0  22.0     1   0         A/5 21171   7.2500   NaN   S    23  
1  38.0     1   0          PC 17599  71.2833   C85   C    51  
2  26.0     0   0  STON/O2. 3101282   7.9250   NaN   S    22  
3  35.0     1   0            113803  53.1000  C123   S    44  
4  35.0     0   0            373450   8.0500   NaN   S    24

In [100]:
#pd에서 np로!
df.to_numpy()

array([[1, 0, 3, ..., nan, 'S', 23],
       [2, 1, 1, ..., 'C85', 'C', 51],
       [3, 1, 3, ..., nan, 'S', 22],
       ...,
       [889, 0, 3, ..., nan, 'S', 40],
       [890, 1, 1, ..., 'C148', 'C', 21],
       [891, 0, 3, ..., nan, 'Q', 19]], dtype=object)

In [101]:
#요약 통계 추출에도 용이!

#Numeric 데이터에 대해서는
df.describe()

아이디          생존        객실등급          나이        형제자매          부모  \
count  891.000000  891.000000  891.000000  714.000000  891.000000  891.000000   
mean   446.000000    0.383838    2.308642   29.699118    0.523008    0.381594   
std    257.353842    0.486592    0.836071   14.526497    1.102743    0.806057   
min      1.000000    0.000000    1.000000    0.420000    0.000000    0.000000   
25%    223.500000    0.000000    2.000000   20.125000    0.000000    0.000000   
50%    446.000000    0.000000    3.000000   28.000000    0.000000    0.000000   
75%    668.500000    1.000000    3.000000   38.000000    1.000000    0.000000   
max    891.000000    1.000000    3.000000   80.000000    8.000000    6.000000   

               요금        이름길이  
count  891.000000  891.000000  
mean    32.204208   26.965208  
std     49.693429    9.281607  
min      0.000000   12.000000  
25%      7.910400   20.000000  
50%     14.454200   25.000000  
75%     31.000000   30.000000  
max    512.329200   82.000000

In [107]:
#Categorical Data에 대해서는 빈도수
print(df['성별'].value_counts())
print(df['승선항'].value_counts())
print(df['객실등급'].value_counts())

male      577
female    314
Name: 성별, dtype: int64
S    644
C    168
Q     77
Name: 승선항, dtype: int64
3    491
1    216
2    184
Name: 객실등급, dtype: int64
